[E]	manager_0@10.0.1.101	2018-10-18 10:57:46.377499 +0800	1539831466	leo_manager_cluster_monitor:register_fun_1/2	517	[{cause,"Mnesia is not available"}]
[E]	manager_0@10.0.1.101	2018-10-18 10:58:06.417463 +0800	1539831486	null:null	0	CRASH REPORT Process <0.3137.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 10:58:06.418114 +0800	1539831486	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 10:58:06.418272 +0800	1539831486	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 10:58:06.418399 +0800	1539831486	null:null	0	gen_server leo_rpc_client_manager terminated with reason: {{connection_error,{connection_error,econnrefused}},{gen_server,call,[<0.3136.0>,raw_status]}} in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:58:06.418502 +0800	1539831486	null:null	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: {{connection_error,{connection_error,econnrefused}},{gen_server,call,[<0.3136.0>,raw_status]}} in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:58:06.418649 +0800	1539831486	null:null	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.823.0> exit with reason {{connection_error,{connection_error,econnrefused}},{gen_server,call,[<0.3136.0>,raw_status]}} in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 10:58:06.454686 +0800	1539831486	null:null	0	CRASH REPORT Process <0.3143.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 10:58:06.454913 +0800	1539831486	null:null	0	Supervisor leo_rpc_client_manager_10_at_13075_sup had child leo_rpc_client_manager_10_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_10_at_13075, 16, 16, leo_rpc_client_conn, [manager_10,"10.16.2.223",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 10:58:06.455054 +0800	1539831486	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_10_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_10_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_10_at_13075,16,16,leo_rpc_client_conn,[manager_10,"10.16.2.223",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 10:58:11.418834 +0800	1539831491	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:58:11.419317 +0800	1539831491	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:58:11.419473 +0800	1539831491	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3139.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 10:58:16.388645 +0800	1539831496	null:null	0	CRASH REPORT Process <0.3298.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 10:58:16.389474 +0800	1539831496	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 10:58:16.389598 +0800	1539831496	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 10:58:16.419757 +0800	1539831496	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:58:16.419939 +0800	1539831496	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:58:16.420222 +0800	1539831496	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3252.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 10:58:21.420748 +0800	1539831501	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:58:21.421146 +0800	1539831501	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:58:21.421301 +0800	1539831501	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3303.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 10:58:26.422717 +0800	1539831506	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:58:26.423390 +0800	1539831506	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:58:26.423626 +0800	1539831506	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3417.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 10:58:26.491630 +0800	1539831506	null:null	0	CRASH REPORT Process <0.3457.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 10:58:26.492102 +0800	1539831506	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 10:58:26.492280 +0800	1539831506	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 10:58:31.424880 +0800	1539831511	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:58:31.425318 +0800	1539831511	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:58:31.425478 +0800	1539831511	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3452.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 10:58:36.426936 +0800	1539831516	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:58:36.427682 +0800	1539831516	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:58:36.428098 +0800	1539831516	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3557.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 10:58:41.428831 +0800	1539831521	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:58:41.429281 +0800	1539831521	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:58:41.429465 +0800	1539831521	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3615.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 10:58:46.428445 +0800	1539831526	null:null	0	CRASH REPORT Process <0.3774.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 10:58:46.429518 +0800	1539831526	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 10:58:46.429658 +0800	1539831526	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 10:58:46.429819 +0800	1539831526	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:58:46.429944 +0800	1539831526	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:58:46.430107 +0800	1539831526	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3694.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 10:58:46.530010 +0800	1539831526	null:null	0	CRASH REPORT Process <0.3784.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 10:58:46.530269 +0800	1539831526	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 10:58:46.530432 +0800	1539831526	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 10:58:51.430776 +0800	1539831531	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:58:51.431343 +0800	1539831531	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:58:51.431582 +0800	1539831531	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3779.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 10:58:56.432813 +0800	1539831536	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:58:56.433463 +0800	1539831536	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:58:56.433799 +0800	1539831536	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3865.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 10:59:01.433765 +0800	1539831541	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:59:01.434403 +0800	1539831541	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:59:01.434653 +0800	1539831541	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3952.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 10:59:06.435694 +0800	1539831546	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:59:06.436407 +0800	1539831546	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:59:06.436575 +0800	1539831546	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4029.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 10:59:06.568477 +0800	1539831546	null:null	0	CRASH REPORT Process <0.4108.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 10:59:06.568972 +0800	1539831546	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 10:59:06.569105 +0800	1539831546	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 10:59:11.437012 +0800	1539831551	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:59:11.437704 +0800	1539831551	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:59:11.438017 +0800	1539831551	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4103.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 10:59:16.438650 +0800	1539831556	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:59:16.439394 +0800	1539831556	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:59:16.467864 +0800	1539831556	null:null	0	CRASH REPORT Process <0.4279.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 10:59:16.468336 +0800	1539831556	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 10:59:16.468685 +0800	1539831556	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4195.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 10:59:16.468868 +0800	1539831556	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 10:59:21.469809 +0800	1539831561	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:59:21.470137 +0800	1539831561	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:59:21.470425 +0800	1539831561	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4281.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 10:59:26.471804 +0800	1539831566	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:59:26.472313 +0800	1539831566	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:59:26.472602 +0800	1539831566	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4362.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 10:59:26.606215 +0800	1539831566	null:null	0	CRASH REPORT Process <0.4444.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 10:59:26.606813 +0800	1539831566	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 10:59:26.607023 +0800	1539831566	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 10:59:31.473785 +0800	1539831571	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:59:31.474340 +0800	1539831571	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:59:31.474550 +0800	1539831571	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4439.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 10:59:36.475746 +0800	1539831576	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:59:36.476097 +0800	1539831576	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:59:36.476284 +0800	1539831576	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4521.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 10:59:41.478058 +0800	1539831581	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:59:41.478488 +0800	1539831581	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:59:41.478650 +0800	1539831581	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4596.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 10:59:46.479708 +0800	1539831586	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:59:46.480046 +0800	1539831586	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:59:46.508108 +0800	1539831586	null:null	0	CRASH REPORT Process <0.4744.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 10:59:46.508513 +0800	1539831586	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 10:59:46.508666 +0800	1539831586	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4673.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 10:59:46.508805 +0800	1539831586	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 10:59:46.645843 +0800	1539831586	null:null	0	CRASH REPORT Process <0.4754.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 10:59:46.646177 +0800	1539831586	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 10:59:46.646332 +0800	1539831586	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 10:59:51.509743 +0800	1539831591	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:59:51.510268 +0800	1539831591	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:59:51.510534 +0800	1539831591	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4746.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 10:59:56.511786 +0800	1539831596	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 10:59:56.512409 +0800	1539831596	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 10:59:56.512743 +0800	1539831596	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4812.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
