[E]	manager_0@10.0.1.101	2018-10-18 11:51:01.371076 +0800	1539834661	null:null	0	CRASH REPORT Process <0.3125.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:51:01.371957 +0800	1539834661	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:51:01.372104 +0800	1539834661	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:51:01.372233 +0800	1539834661	null:null	0	gen_server leo_rpc_client_manager terminated with reason: {{connection_error,{connection_error,econnrefused}},{gen_server,call,[<0.3124.0>,raw_status]}} in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:51:01.372336 +0800	1539834661	null:null	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: {{connection_error,{connection_error,econnrefused}},{gen_server,call,[<0.3124.0>,raw_status]}} in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:51:01.372481 +0800	1539834661	null:null	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.818.0> exit with reason {{connection_error,{connection_error,econnrefused}},{gen_server,call,[<0.3124.0>,raw_status]}} in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:51:01.407244 +0800	1539834661	null:null	0	CRASH REPORT Process <0.3131.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:51:01.407492 +0800	1539834661	null:null	0	Supervisor leo_rpc_client_manager_10_at_13075_sup had child leo_rpc_client_manager_10_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_10_at_13075, 16, 16, leo_rpc_client_conn, [manager_10,"10.16.2.223",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:51:01.407659 +0800	1539834661	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_10_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_10_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_10_at_13075,16,16,leo_rpc_client_conn,[manager_10,"10.16.2.223",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:51:06.372221 +0800	1539834666	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:51:06.372835 +0800	1539834666	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:51:06.373075 +0800	1539834666	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3127.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:51:11.343982 +0800	1539834671	null:null	0	{module,"leo_pod_manager"},{function,"start_child/2"},{line,324},{body,{connection_error,{connection_error,econnrefused}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:51:11.344453 +0800	1539834671	null:null	0	CRASH REPORT Process <0.3283.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:51:11.345047 +0800	1539834671	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:51:11.345350 +0800	1539834671	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:51:11.373153 +0800	1539834671	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:51:11.373332 +0800	1539834671	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:51:11.373495 +0800	1539834671	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3239.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:51:16.374119 +0800	1539834676	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:51:16.374618 +0800	1539834676	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:51:16.374896 +0800	1539834676	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3289.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:51:21.376414 +0800	1539834681	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:51:21.377124 +0800	1539834681	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:51:21.377357 +0800	1539834681	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3407.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:51:21.445834 +0800	1539834681	null:null	0	CRASH REPORT Process <0.3455.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:51:21.446094 +0800	1539834681	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:51:21.446214 +0800	1539834681	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:51:26.377215 +0800	1539834686	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:51:26.377864 +0800	1539834686	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:51:26.378092 +0800	1539834686	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3448.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:51:31.379222 +0800	1539834691	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:51:31.379599 +0800	1539834691	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:51:31.379856 +0800	1539834691	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3580.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:51:36.380210 +0800	1539834696	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:51:36.380763 +0800	1539834696	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:51:36.381010 +0800	1539834696	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3617.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:51:41.382144 +0800	1539834701	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:51:41.382679 +0800	1539834701	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:51:41.384836 +0800	1539834701	null:null	0	CRASH REPORT Process <0.3784.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:51:41.385255 +0800	1539834701	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:51:41.385403 +0800	1539834701	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3712.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:51:41.385522 +0800	1539834701	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:51:41.486898 +0800	1539834701	null:null	0	CRASH REPORT Process <0.3794.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:51:41.487435 +0800	1539834701	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:51:41.487623 +0800	1539834701	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:51:46.386258 +0800	1539834706	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:51:46.386608 +0800	1539834706	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:51:46.386796 +0800	1539834706	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3786.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:51:51.388198 +0800	1539834711	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:51:51.388659 +0800	1539834711	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:51:51.388864 +0800	1539834711	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3925.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:51:56.389262 +0800	1539834716	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:51:56.389705 +0800	1539834716	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:51:56.389926 +0800	1539834716	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.3985.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:52:01.391181 +0800	1539834721	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:52:01.391902 +0800	1539834721	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:52:01.392098 +0800	1539834721	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4084.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:52:01.525328 +0800	1539834721	null:null	0	CRASH REPORT Process <0.4151.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:52:01.525904 +0800	1539834721	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:52:01.526109 +0800	1539834721	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:52:06.393174 +0800	1539834726	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:52:06.393777 +0800	1539834726	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:52:06.394014 +0800	1539834726	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4146.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:52:11.395055 +0800	1539834731	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:52:11.395439 +0800	1539834731	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:52:11.423318 +0800	1539834731	null:null	0	CRASH REPORT Process <0.4311.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:52:11.423665 +0800	1539834731	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:52:11.423852 +0800	1539834731	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4243.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:52:11.423995 +0800	1539834731	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:52:16.425184 +0800	1539834736	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:52:16.425888 +0800	1539834736	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:52:16.426138 +0800	1539834736	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4313.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:52:21.427119 +0800	1539834741	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:52:21.427409 +0800	1539834741	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:52:21.427600 +0800	1539834741	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4409.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:52:21.563757 +0800	1539834741	null:null	0	CRASH REPORT Process <0.4473.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:52:21.563992 +0800	1539834741	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:52:21.564133 +0800	1539834741	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:52:26.429226 +0800	1539834746	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:52:26.429621 +0800	1539834746	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:52:26.429796 +0800	1539834746	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4458.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:52:31.431234 +0800	1539834751	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:52:31.431706 +0800	1539834751	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:52:31.431987 +0800	1539834751	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4555.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:52:36.433089 +0800	1539834756	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:52:36.433584 +0800	1539834756	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:52:36.433859 +0800	1539834756	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4609.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:52:41.435091 +0800	1539834761	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:52:41.435737 +0800	1539834761	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:52:41.462545 +0800	1539834761	null:null	0	CRASH REPORT Process <0.4772.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:52:41.462935 +0800	1539834761	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:52:41.463090 +0800	1539834761	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4694.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:52:41.463220 +0800	1539834761	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:52:41.602280 +0800	1539834761	null:null	0	CRASH REPORT Process <0.4782.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:52:41.602514 +0800	1539834761	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:52:41.602636 +0800	1539834761	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:52:46.464208 +0800	1539834766	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:52:46.464602 +0800	1539834766	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:52:46.464794 +0800	1539834766	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4774.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:52:51.466191 +0800	1539834771	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:52:51.466936 +0800	1539834771	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:52:51.467219 +0800	1539834771	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4885.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:52:56.468265 +0800	1539834776	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:52:56.469165 +0800	1539834776	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:52:56.469392 +0800	1539834776	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4952.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:53:01.470178 +0800	1539834781	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:53:01.470824 +0800	1539834781	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:53:01.471054 +0800	1539834781	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4998.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:53:01.642164 +0800	1539834781	null:null	0	CRASH REPORT Process <0.5111.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:53:01.642766 +0800	1539834781	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:53:01.642931 +0800	1539834781	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:53:06.472208 +0800	1539834786	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:53:06.472623 +0800	1539834786	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:53:06.472805 +0800	1539834786	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5106.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:53:11.474169 +0800	1539834791	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:53:11.474750 +0800	1539834791	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:53:11.501165 +0800	1539834791	null:null	0	CRASH REPORT Process <0.5268.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:53:11.501498 +0800	1539834791	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:53:11.501673 +0800	1539834791	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5149.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:53:11.501835 +0800	1539834791	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:53:16.503164 +0800	1539834796	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:53:16.503602 +0800	1539834796	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:53:16.503777 +0800	1539834796	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5270.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:53:21.505609 +0800	1539834801	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:53:21.506101 +0800	1539834801	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:53:21.506261 +0800	1539834801	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5314.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:53:21.681218 +0800	1539834801	null:null	0	CRASH REPORT Process <0.5434.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:53:21.681529 +0800	1539834801	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:53:21.681663 +0800	1539834801	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:53:26.507176 +0800	1539834806	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:53:26.507548 +0800	1539834806	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:53:26.507721 +0800	1539834806	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5427.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:53:31.509383 +0800	1539834811	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:53:31.509978 +0800	1539834811	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:53:31.510148 +0800	1539834811	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5478.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:53:36.511169 +0800	1539834816	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:53:36.511944 +0800	1539834816	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:53:36.512148 +0800	1539834816	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5587.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:53:41.513085 +0800	1539834821	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:53:41.513705 +0800	1539834821	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:53:41.540093 +0800	1539834821	null:null	0	CRASH REPORT Process <0.5766.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:53:41.540712 +0800	1539834821	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:53:41.540907 +0800	1539834821	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5630.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:53:41.541050 +0800	1539834821	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:53:41.719199 +0800	1539834821	null:null	0	CRASH REPORT Process <0.5776.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:53:41.719545 +0800	1539834821	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:53:41.719739 +0800	1539834821	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:53:46.542379 +0800	1539834826	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:53:46.543124 +0800	1539834826	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:53:46.543507 +0800	1539834826	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5768.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:53:51.544322 +0800	1539834831	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:53:51.544830 +0800	1539834831	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:53:51.545075 +0800	1539834831	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5840.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:53:56.545139 +0800	1539834836	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:53:56.545837 +0800	1539834836	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:53:56.546035 +0800	1539834836	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5955.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:54:01.547253 +0800	1539834841	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:54:01.547859 +0800	1539834841	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:54:01.548126 +0800	1539834841	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5997.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:54:01.757940 +0800	1539834841	null:null	0	{module,"leo_pod_manager"},{function,"start_child/2"},{line,324},{body,{connection_error,{connection_error,econnrefused}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:54:01.758119 +0800	1539834841	null:null	0	CRASH REPORT Process <0.6098.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:54:01.758327 +0800	1539834841	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:54:01.758512 +0800	1539834841	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:54:06.549127 +0800	1539834846	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:54:06.549586 +0800	1539834846	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:54:06.549781 +0800	1539834846	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6091.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:54:11.551147 +0800	1539834851	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:54:11.551631 +0800	1539834851	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:54:11.578864 +0800	1539834851	null:null	0	CRASH REPORT Process <0.6244.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:54:11.579183 +0800	1539834851	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:54:11.579330 +0800	1539834851	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6153.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:54:11.579451 +0800	1539834851	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:54:16.580215 +0800	1539834856	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:54:16.580792 +0800	1539834856	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:54:16.581035 +0800	1539834856	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6246.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:54:21.582229 +0800	1539834861	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:54:21.582861 +0800	1539834861	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:54:21.583116 +0800	1539834861	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6307.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:54:21.796395 +0800	1539834861	null:null	0	CRASH REPORT Process <0.6406.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:54:21.797151 +0800	1539834861	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:54:21.797369 +0800	1539834861	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:54:26.584263 +0800	1539834866	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:54:26.584624 +0800	1539834866	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:54:26.584806 +0800	1539834866	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6401.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:54:31.586244 +0800	1539834871	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:54:31.586527 +0800	1539834871	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:54:31.586681 +0800	1539834871	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6467.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:54:36.588141 +0800	1539834876	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:54:36.588722 +0800	1539834876	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:54:36.588932 +0800	1539834876	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6571.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:54:41.590111 +0800	1539834881	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:54:41.590945 +0800	1539834881	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:54:41.618861 +0800	1539834881	null:null	0	{module,"leo_pod_manager"},{function,"start_child/2"},{line,324},{body,{connection_error,{connection_error,econnrefused}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:54:41.619109 +0800	1539834881	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:54:41.619217 +0800	1539834881	null:null	0	CRASH REPORT Process <0.6724.0> with 0 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:54:41.619373 +0800	1539834881	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6623.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:54:41.619539 +0800	1539834881	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:54:41.840881 +0800	1539834881	null:null	0	{module,"leo_pod_manager"},{function,"start_child/2"},{line,324},{body,{connection_error,{connection_error,econnrefused}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:54:41.841011 +0800	1539834881	null:null	0	CRASH REPORT Process <0.6733.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:54:41.841218 +0800	1539834881	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:54:41.841355 +0800	1539834881	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:54:46.620268 +0800	1539834886	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:54:46.620808 +0800	1539834886	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:54:46.621065 +0800	1539834886	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6726.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:54:51.622126 +0800	1539834891	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:54:51.622470 +0800	1539834891	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:54:51.622618 +0800	1539834891	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6812.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:54:56.623228 +0800	1539834896	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:54:56.623799 +0800	1539834896	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:54:56.624007 +0800	1539834896	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6900.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:55:01.624293 +0800	1539834901	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:55:01.625008 +0800	1539834901	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:55:01.625280 +0800	1539834901	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6957.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:55:01.879036 +0800	1539834901	null:null	0	{module,"leo_pod_manager"},{function,"start_child/2"},{line,324},{body,{connection_error,{connection_error,econnrefused}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:55:01.879178 +0800	1539834901	null:null	0	CRASH REPORT Process <0.7020.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:55:01.879383 +0800	1539834901	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:55:01.879521 +0800	1539834901	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:55:06.626267 +0800	1539834906	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:55:06.626609 +0800	1539834906	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:55:06.626816 +0800	1539834906	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7000.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:55:11.628050 +0800	1539834911	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:55:11.628581 +0800	1539834911	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:55:11.657554 +0800	1539834911	null:null	0	{module,"leo_pod_manager"},{function,"start_child/2"},{line,324},{body,{connection_error,{connection_error,econnrefused}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:55:11.657748 +0800	1539834911	null:null	0	CRASH REPORT Process <0.7165.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:55:11.657956 +0800	1539834911	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:55:11.658106 +0800	1539834911	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7113.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:55:11.658227 +0800	1539834911	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:55:16.659204 +0800	1539834916	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:55:16.659550 +0800	1539834916	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:55:16.659720 +0800	1539834916	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7168.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:55:21.661211 +0800	1539834921	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:55:21.661754 +0800	1539834921	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:55:21.662006 +0800	1539834921	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7278.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:55:21.916097 +0800	1539834921	null:null	0	CRASH REPORT Process <0.7324.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:55:21.916468 +0800	1539834921	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:55:21.916630 +0800	1539834921	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:55:26.663133 +0800	1539834926	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:55:26.663503 +0800	1539834926	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:55:26.663655 +0800	1539834926	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7319.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:55:31.665172 +0800	1539834931	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:55:31.665510 +0800	1539834931	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:55:31.665695 +0800	1539834931	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7436.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:55:36.667185 +0800	1539834936	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:55:36.667662 +0800	1539834936	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:55:36.667913 +0800	1539834936	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7482.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:55:41.669154 +0800	1539834941	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:55:41.669920 +0800	1539834941	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:55:41.696665 +0800	1539834941	null:null	0	CRASH REPORT Process <0.7646.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:55:41.697316 +0800	1539834941	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:55:41.697559 +0800	1539834941	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7596.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:55:41.697771 +0800	1539834941	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:55:41.953621 +0800	1539834941	null:null	0	CRASH REPORT Process <0.7656.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:55:41.954092 +0800	1539834941	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:55:41.954337 +0800	1539834941	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:55:46.698154 +0800	1539834946	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:55:46.698783 +0800	1539834946	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:55:46.699027 +0800	1539834946	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7648.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:55:51.700279 +0800	1539834951	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:55:51.701083 +0800	1539834951	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:55:51.701350 +0800	1539834951	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7811.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:55:56.702161 +0800	1539834956	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:55:56.702787 +0800	1539834956	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:55:56.703067 +0800	1539834956	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7850.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:56:01.704199 +0800	1539834961	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:56:01.705036 +0800	1539834961	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:56:01.705231 +0800	1539834961	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7963.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:56:01.992790 +0800	1539834961	null:null	0	CRASH REPORT Process <0.8009.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:56:01.993551 +0800	1539834961	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:56:01.993767 +0800	1539834961	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:56:06.706212 +0800	1539834966	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:56:06.706866 +0800	1539834966	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:56:06.707097 +0800	1539834966	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8004.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:56:11.708036 +0800	1539834971	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:56:11.708655 +0800	1539834971	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:56:11.735520 +0800	1539834971	null:null	0	CRASH REPORT Process <0.8156.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:56:11.735979 +0800	1539834971	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:56:11.736128 +0800	1539834971	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8122.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:56:11.736250 +0800	1539834971	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:56:16.737419 +0800	1539834976	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:56:16.737996 +0800	1539834976	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:56:16.738238 +0800	1539834976	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8161.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:56:21.739159 +0800	1539834981	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:56:21.739720 +0800	1539834981	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:56:21.739898 +0800	1539834981	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8273.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:56:22.32565 +0800	1539834982	null:null	0	CRASH REPORT Process <0.8316.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:56:22.33188 +0800	1539834982	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:56:22.33346 +0800	1539834982	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:56:26.741279 +0800	1539834986	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:56:26.741707 +0800	1539834986	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:56:26.742019 +0800	1539834986	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8311.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:56:31.743178 +0800	1539834991	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:56:31.743513 +0800	1539834991	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:56:31.743680 +0800	1539834991	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8413.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:56:36.745163 +0800	1539834996	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:56:36.745774 +0800	1539834996	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:56:36.746050 +0800	1539834996	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8471.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:56:41.747041 +0800	1539835001	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:56:41.747633 +0800	1539835001	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:56:41.775692 +0800	1539835001	null:null	0	CRASH REPORT Process <0.8628.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:56:41.776419 +0800	1539835001	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:56:41.776809 +0800	1539835001	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8565.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:56:41.777125 +0800	1539835001	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:56:42.71351 +0800	1539835002	null:null	0	CRASH REPORT Process <0.8638.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:56:42.71591 +0800	1539835002	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:56:42.71717 +0800	1539835002	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:56:46.778163 +0800	1539835006	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:56:46.778515 +0800	1539835006	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:56:46.778698 +0800	1539835006	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8630.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:56:51.780125 +0800	1539835011	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:56:51.780401 +0800	1539835011	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:56:51.780562 +0800	1539835011	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8756.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:56:56.782160 +0800	1539835016	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:56:56.782828 +0800	1539835016	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:56:56.783110 +0800	1539835016	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8807.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:57:01.784126 +0800	1539835021	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:57:01.784719 +0800	1539835021	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:57:01.784967 +0800	1539835021	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8894.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:57:02.112190 +0800	1539835022	null:null	0	CRASH REPORT Process <0.8965.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:57:02.112836 +0800	1539835022	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:57:02.113071 +0800	1539835022	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:57:06.786185 +0800	1539835026	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:57:06.787027 +0800	1539835026	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:57:06.787199 +0800	1539835026	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8960.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:57:11.788230 +0800	1539835031	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:57:11.788876 +0800	1539835031	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:57:11.815208 +0800	1539835031	null:null	0	CRASH REPORT Process <0.9116.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:57:11.815676 +0800	1539835031	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:57:11.815941 +0800	1539835031	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9016.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:57:11.816189 +0800	1539835031	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:57:16.817566 +0800	1539835036	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:57:16.818086 +0800	1539835036	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:57:16.818241 +0800	1539835036	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9118.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:57:21.819156 +0800	1539835041	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:57:21.819575 +0800	1539835041	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:57:21.819715 +0800	1539835041	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9177.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:57:22.150158 +0800	1539835042	null:null	0	CRASH REPORT Process <0.9279.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:57:22.150403 +0800	1539835042	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:57:22.150535 +0800	1539835042	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:57:26.821235 +0800	1539835046	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:57:26.821638 +0800	1539835046	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:57:26.821816 +0800	1539835046	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9274.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:57:31.823158 +0800	1539835051	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:57:31.823774 +0800	1539835051	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:57:31.823962 +0800	1539835051	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9318.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:57:36.824194 +0800	1539835056	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:57:36.824627 +0800	1539835056	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:57:36.824811 +0800	1539835056	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9430.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:57:41.826112 +0800	1539835061	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:57:41.826654 +0800	1539835061	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:57:41.854996 +0800	1539835061	null:null	0	CRASH REPORT Process <0.9589.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:57:41.855481 +0800	1539835061	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:57:41.855638 +0800	1539835061	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9469.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:57:41.855793 +0800	1539835061	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:57:42.188951 +0800	1539835062	null:null	0	CRASH REPORT Process <0.9601.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:57:42.189179 +0800	1539835062	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:57:42.189323 +0800	1539835062	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:57:46.857222 +0800	1539835066	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:57:46.857590 +0800	1539835066	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:57:46.857762 +0800	1539835066	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9591.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:57:51.859196 +0800	1539835071	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:57:51.859558 +0800	1539835071	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:57:51.859799 +0800	1539835071	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9668.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:57:56.861206 +0800	1539835076	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:57:56.862001 +0800	1539835076	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:57:56.862175 +0800	1539835076	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9772.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:58:01.863043 +0800	1539835081	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:58:01.863625 +0800	1539835081	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:58:01.863869 +0800	1539835081	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9814.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:58:02.226280 +0800	1539835082	null:null	0	CRASH REPORT Process <0.9930.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:58:02.226860 +0800	1539835082	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:58:02.227010 +0800	1539835082	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:58:06.865124 +0800	1539835086	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:58:06.865627 +0800	1539835086	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:58:06.865890 +0800	1539835086	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9915.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:58:11.867125 +0800	1539835091	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:58:11.867692 +0800	1539835091	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:58:11.894805 +0800	1539835091	null:null	0	CRASH REPORT Process <0.10079.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:58:11.895255 +0800	1539835091	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:58:11.895422 +0800	1539835091	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9955.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:58:11.895576 +0800	1539835091	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:58:16.896172 +0800	1539835096	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:58:16.896628 +0800	1539835096	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:58:16.896809 +0800	1539835096	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10081.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:58:21.898201 +0800	1539835101	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:58:21.898695 +0800	1539835101	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:58:21.898960 +0800	1539835101	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10124.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:58:22.264298 +0800	1539835102	null:null	0	CRASH REPORT Process <0.10243.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:58:22.264707 +0800	1539835102	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:58:22.264859 +0800	1539835102	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:58:26.900216 +0800	1539835106	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:58:26.900758 +0800	1539835106	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:58:26.901014 +0800	1539835106	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10238.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:58:31.902521 +0800	1539835111	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:58:31.903023 +0800	1539835111	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:58:31.903211 +0800	1539835111	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10281.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:58:36.904168 +0800	1539835116	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:58:36.904817 +0800	1539835116	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:58:36.905017 +0800	1539835116	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10396.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:58:41.906067 +0800	1539835121	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:58:41.906519 +0800	1539835121	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:58:41.934469 +0800	1539835121	null:null	0	CRASH REPORT Process <0.10548.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:58:41.934923 +0800	1539835121	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:58:41.935188 +0800	1539835121	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10433.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:58:41.935366 +0800	1539835121	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:58:42.301765 +0800	1539835122	null:null	0	CRASH REPORT Process <0.10562.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:58:42.302159 +0800	1539835122	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:58:42.302322 +0800	1539835122	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:58:46.936101 +0800	1539835126	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:58:46.936449 +0800	1539835126	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:58:46.936608 +0800	1539835126	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10550.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:58:51.937520 +0800	1539835131	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:58:51.938863 +0800	1539835131	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:58:51.939339 +0800	1539835131	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10626.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:58:56.939159 +0800	1539835136	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:58:56.939498 +0800	1539835136	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:58:56.939654 +0800	1539835136	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10718.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:59:01.940042 +0800	1539835141	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:59:01.940578 +0800	1539835141	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:59:01.940931 +0800	1539835141	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10782.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:59:02.340932 +0800	1539835142	null:null	0	CRASH REPORT Process <0.10878.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:59:02.341362 +0800	1539835142	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:59:02.341526 +0800	1539835142	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:59:06.942121 +0800	1539835146	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:59:06.942587 +0800	1539835146	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:59:06.942872 +0800	1539835146	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10854.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:59:11.944015 +0800	1539835151	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:59:11.944657 +0800	1539835151	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:59:11.973519 +0800	1539835151	null:null	0	{module,"leo_pod_manager"},{function,"start_child/2"},{line,324},{body,{connection_error,{connection_error,econnrefused}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:59:11.973876 +0800	1539835151	null:null	0	CRASH REPORT Process <0.10999.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:59:11.974322 +0800	1539835151	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:59:11.974501 +0800	1539835151	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10939.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:59:11.974654 +0800	1539835151	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:59:16.975291 +0800	1539835156	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:59:16.975676 +0800	1539835156	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:59:16.975833 +0800	1539835156	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11003.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:59:21.977089 +0800	1539835161	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:59:21.977611 +0800	1539835161	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:59:21.977806 +0800	1539835161	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11100.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:59:22.379519 +0800	1539835162	null:null	0	CRASH REPORT Process <0.11164.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:59:22.380389 +0800	1539835162	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:59:22.380711 +0800	1539835162	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:59:26.978241 +0800	1539835166	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:59:26.978598 +0800	1539835166	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:59:26.978797 +0800	1539835166	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11159.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:59:31.980274 +0800	1539835171	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:59:31.980620 +0800	1539835171	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:59:31.980809 +0800	1539835171	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11260.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:59:36.982255 +0800	1539835176	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:59:36.982671 +0800	1539835176	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:59:36.982923 +0800	1539835176	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11316.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:59:41.984107 +0800	1539835181	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:59:41.984749 +0800	1539835181	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:59:42.15233 +0800	1539835182	null:null	0	CRASH REPORT Process <0.11477.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:59:42.15532 +0800	1539835182	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:59:42.15684 +0800	1539835182	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11408.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:59:42.15821 +0800	1539835182	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:59:42.418015 +0800	1539835182	null:null	0	CRASH REPORT Process <0.11491.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:59:42.418271 +0800	1539835182	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:59:42.418462 +0800	1539835182	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:59:47.17230 +0800	1539835187	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:59:47.17521 +0800	1539835187	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:59:47.17673 +0800	1539835187	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11480.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:59:52.19171 +0800	1539835192	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:59:52.19589 +0800	1539835192	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:59:52.19790 +0800	1539835192	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11604.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:59:57.21238 +0800	1539835197	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:59:57.21843 +0800	1539835197	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:59:57.22048 +0800	1539835197	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11654.0> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
