[E]	manager_0@10.0.1.101	2018-10-18 11:00:01.513758 +0800	1539831601	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:00:01.514385 +0800	1539831601	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:00:01.514591 +0800	1539831601	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4929.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:00:06.515849 +0800	1539831606	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:00:06.516659 +0800	1539831606	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:00:06.516927 +0800	1539831606	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.4970.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:00:06.684798 +0800	1539831606	null:null	0	CRASH REPORT Process <0.5089.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:00:06.685308 +0800	1539831606	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:00:06.685471 +0800	1539831606	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:00:11.518344 +0800	1539831611	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:00:11.518675 +0800	1539831611	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:00:11.518863 +0800	1539831611	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5084.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:00:16.519627 +0800	1539831616	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:00:16.520338 +0800	1539831616	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:00:16.545680 +0800	1539831616	null:null	0	CRASH REPORT Process <0.5254.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:00:16.546194 +0800	1539831616	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:00:16.546391 +0800	1539831616	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5131.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:00:16.546553 +0800	1539831616	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:00:21.547818 +0800	1539831621	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:00:21.548328 +0800	1539831621	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:00:21.548491 +0800	1539831621	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5256.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:00:26.549929 +0800	1539831626	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:00:26.550331 +0800	1539831626	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:00:26.550524 +0800	1539831626	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5298.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:00:26.723930 +0800	1539831626	null:null	0	CRASH REPORT Process <0.5414.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:00:26.724383 +0800	1539831626	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:00:26.724514 +0800	1539831626	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:00:31.551826 +0800	1539831631	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:00:31.552238 +0800	1539831631	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:00:31.552408 +0800	1539831631	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5406.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:00:36.553803 +0800	1539831636	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:00:36.554264 +0800	1539831636	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:00:36.554437 +0800	1539831636	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5453.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:00:41.554923 +0800	1539831641	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:00:41.555465 +0800	1539831641	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:00:41.555673 +0800	1539831641	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5568.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:00:46.556633 +0800	1539831646	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:00:46.557166 +0800	1539831646	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:00:46.586947 +0800	1539831646	null:null	0	CRASH REPORT Process <0.5744.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:00:46.587426 +0800	1539831646	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:00:46.587572 +0800	1539831646	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5607.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:00:46.587724 +0800	1539831646	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:00:46.761680 +0800	1539831646	null:null	0	CRASH REPORT Process <0.5757.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:00:46.762155 +0800	1539831646	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:00:46.762347 +0800	1539831646	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:00:51.588845 +0800	1539831651	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:00:51.589559 +0800	1539831651	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:00:51.589936 +0800	1539831651	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5746.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:00:56.590858 +0800	1539831656	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:00:56.591498 +0800	1539831656	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:00:56.591676 +0800	1539831656	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5796.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:01:01.592863 +0800	1539831661	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:01:01.593695 +0800	1539831661	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:01:01.593917 +0800	1539831661	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5911.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:01:06.594793 +0800	1539831666	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:01:06.595386 +0800	1539831666	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:01:06.595662 +0800	1539831666	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.5969.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:01:06.807552 +0800	1539831666	null:null	0	CRASH REPORT Process <0.6065.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:01:06.808031 +0800	1539831666	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:01:06.808198 +0800	1539831666	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:01:11.596820 +0800	1539831671	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:01:11.597113 +0800	1539831671	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:01:11.597287 +0800	1539831671	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6060.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:01:16.598638 +0800	1539831676	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:01:16.599234 +0800	1539831676	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:01:16.627932 +0800	1539831676	null:null	0	CRASH REPORT Process <0.6211.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:01:16.628390 +0800	1539831676	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:01:16.628559 +0800	1539831676	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6122.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:01:16.628684 +0800	1539831676	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:01:21.629787 +0800	1539831681	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:01:21.630414 +0800	1539831681	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:01:21.630637 +0800	1539831681	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6213.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:01:26.631822 +0800	1539831686	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:01:26.632576 +0800	1539831686	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:01:26.632813 +0800	1539831686	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6292.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:01:26.846984 +0800	1539831686	null:null	0	CRASH REPORT Process <0.6375.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:01:26.847347 +0800	1539831686	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:01:26.847549 +0800	1539831686	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:01:31.633828 +0800	1539831691	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:01:31.634387 +0800	1539831691	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:01:31.634665 +0800	1539831691	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6370.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:01:36.635757 +0800	1539831696	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:01:36.636039 +0800	1539831696	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:01:36.636197 +0800	1539831696	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6450.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:01:41.637738 +0800	1539831701	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:01:41.638188 +0800	1539831701	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:01:41.638370 +0800	1539831701	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6537.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:01:46.639643 +0800	1539831706	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:01:46.640012 +0800	1539831706	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:01:46.667740 +0800	1539831706	null:null	0	CRASH REPORT Process <0.6668.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:01:46.667973 +0800	1539831706	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:01:46.668137 +0800	1539831706	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6613.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:01:46.668311 +0800	1539831706	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:01:46.886104 +0800	1539831706	null:null	0	CRASH REPORT Process <0.6704.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:01:46.886355 +0800	1539831706	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:01:46.886544 +0800	1539831706	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:01:51.669809 +0800	1539831711	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:01:51.670305 +0800	1539831711	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:01:51.670477 +0800	1539831711	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6673.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:01:56.671816 +0800	1539831716	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:01:56.672215 +0800	1539831716	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:01:56.672384 +0800	1539831716	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6765.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:02:01.673842 +0800	1539831721	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:02:01.674362 +0800	1539831721	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:02:01.674599 +0800	1539831721	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6829.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:02:06.675802 +0800	1539831726	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:02:06.676468 +0800	1539831726	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:02:06.676694 +0800	1539831726	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6936.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:02:06.923120 +0800	1539831726	null:null	0	CRASH REPORT Process <0.6981.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:02:06.923693 +0800	1539831726	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:02:06.923839 +0800	1539831726	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:02:11.677967 +0800	1539831731	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:02:11.678294 +0800	1539831731	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:02:11.678437 +0800	1539831731	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.6976.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:02:16.679825 +0800	1539831736	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:02:16.680458 +0800	1539831736	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:02:16.706696 +0800	1539831736	null:null	0	CRASH REPORT Process <0.7137.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:02:16.707210 +0800	1539831736	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:02:16.707374 +0800	1539831736	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7089.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:02:16.707560 +0800	1539831736	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:02:21.708742 +0800	1539831741	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:02:21.709222 +0800	1539831741	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:02:21.709378 +0800	1539831741	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7139.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:02:26.710933 +0800	1539831746	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:02:26.711466 +0800	1539831746	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:02:26.711723 +0800	1539831746	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7251.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:02:26.961856 +0800	1539831746	null:null	0	CRASH REPORT Process <0.7298.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:02:26.962418 +0800	1539831746	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:02:26.962559 +0800	1539831746	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:02:31.712756 +0800	1539831751	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:02:31.713289 +0800	1539831751	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:02:31.713663 +0800	1539831751	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7293.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:02:36.713835 +0800	1539831756	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:02:36.714703 +0800	1539831756	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:02:36.715064 +0800	1539831756	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7409.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:02:41.715723 +0800	1539831761	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:02:41.716393 +0800	1539831761	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:02:41.716615 +0800	1539831761	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7451.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:02:46.717704 +0800	1539831766	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:02:46.718328 +0800	1539831766	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:02:46.747093 +0800	1539831766	null:null	0	CRASH REPORT Process <0.7606.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:02:46.747808 +0800	1539831766	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:02:46.747996 +0800	1539831766	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7560.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:02:46.748128 +0800	1539831766	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:02:47.574 +0800	1539831767	null:null	0	CRASH REPORT Process <0.7616.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:02:47.830 +0800	1539831767	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:02:47.963 +0800	1539831767	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:02:51.748786 +0800	1539831771	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:02:51.749204 +0800	1539831771	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:02:51.749440 +0800	1539831771	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7608.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:02:56.750852 +0800	1539831776	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:02:56.751407 +0800	1539831776	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:02:56.751702 +0800	1539831776	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7727.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:03:01.752833 +0800	1539831781	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:03:01.753290 +0800	1539831781	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:03:01.753466 +0800	1539831781	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7810.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:03:06.754782 +0800	1539831786	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:03:06.755393 +0800	1539831786	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:03:06.755609 +0800	1539831786	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7920.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:03:07.39597 +0800	1539831787	null:null	0	CRASH REPORT Process <0.7972.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:03:07.39892 +0800	1539831787	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:03:07.40058 +0800	1539831787	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:03:11.756850 +0800	1539831791	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:03:11.757348 +0800	1539831791	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:03:11.757591 +0800	1539831791	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.7967.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:03:16.758713 +0800	1539831796	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:03:16.759387 +0800	1539831796	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:03:16.791828 +0800	1539831796	null:null	0	CRASH REPORT Process <0.8127.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:03:16.792118 +0800	1539831796	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:03:16.792286 +0800	1539831796	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8080.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:03:16.792499 +0800	1539831796	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:03:21.793782 +0800	1539831801	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:03:21.794117 +0800	1539831801	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:03:21.794272 +0800	1539831801	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8129.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:03:26.795821 +0800	1539831806	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:03:26.796233 +0800	1539831806	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:03:26.796407 +0800	1539831806	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8221.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:03:27.77111 +0800	1539831807	null:null	0	CRASH REPORT Process <0.8296.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:03:27.77444 +0800	1539831807	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:03:27.77585 +0800	1539831807	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:03:31.797798 +0800	1539831811	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:03:31.798306 +0800	1539831811	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:03:31.798542 +0800	1539831811	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8291.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:03:36.799772 +0800	1539831816	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:03:36.800538 +0800	1539831816	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:03:36.800948 +0800	1539831816	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8376.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:03:41.801805 +0800	1539831821	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:03:41.802420 +0800	1539831821	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:03:41.802665 +0800	1539831821	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8447.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:03:46.803695 +0800	1539831826	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:03:46.804453 +0800	1539831826	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:03:46.831412 +0800	1539831826	null:null	0	CRASH REPORT Process <0.8603.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:03:46.831937 +0800	1539831826	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:03:46.832080 +0800	1539831826	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8506.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:03:46.832216 +0800	1539831826	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:03:47.115778 +0800	1539831827	null:null	0	CRASH REPORT Process <0.8620.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:03:47.116753 +0800	1539831827	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:03:47.117124 +0800	1539831827	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:03:51.832856 +0800	1539831831	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:03:51.833290 +0800	1539831831	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:03:51.833482 +0800	1539831831	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8605.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:03:53.264496 +0800	1539831833	leo_manager_cluster_monitor:handle_call - DOWN	269	[{node,'storage_01@10.0.1.106'}]
[E]	manager_0@10.0.1.101	2018-10-18 11:03:56.834829 +0800	1539831836	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:03:56.835190 +0800	1539831836	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:03:56.835379 +0800	1539831836	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8655.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:04:01.835840 +0800	1539831841	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:04:01.836315 +0800	1539831841	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:04:01.836463 +0800	1539831841	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8788.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:04:06.837767 +0800	1539831846	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:04:06.838254 +0800	1539831846	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:04:06.838500 +0800	1539831846	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8830.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:04:07.154770 +0800	1539831847	null:null	0	CRASH REPORT Process <0.8947.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:04:07.155009 +0800	1539831847	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:04:07.155168 +0800	1539831847	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:04:11.839879 +0800	1539831851	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:04:11.840281 +0800	1539831851	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:04:11.840430 +0800	1539831851	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8942.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:04:16.841715 +0800	1539831856	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:04:16.842251 +0800	1539831856	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:04:16.870368 +0800	1539831856	null:null	0	CRASH REPORT Process <0.9104.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:04:16.870808 +0800	1539831856	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:04:16.870968 +0800	1539831856	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.8985.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:04:16.871107 +0800	1539831856	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:04:21.871923 +0800	1539831861	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:04:21.872718 +0800	1539831861	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:04:21.873100 +0800	1539831861	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9106.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:04:26.873824 +0800	1539831866	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:04:26.874205 +0800	1539831866	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:04:26.874370 +0800	1539831866	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9149.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:04:27.193783 +0800	1539831867	null:null	0	CRASH REPORT Process <0.9275.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:04:27.194275 +0800	1539831867	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:04:27.194448 +0800	1539831867	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:04:31.875764 +0800	1539831871	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:04:31.876101 +0800	1539831871	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:04:31.876248 +0800	1539831871	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9270.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:04:36.877776 +0800	1539831876	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:04:36.878119 +0800	1539831876	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:04:36.878285 +0800	1539831876	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9314.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:04:41.879790 +0800	1539831881	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:04:41.880174 +0800	1539831881	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:04:41.880361 +0800	1539831881	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9429.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:04:46.881624 +0800	1539831886	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:04:46.881957 +0800	1539831886	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:04:46.910787 +0800	1539831886	null:null	0	CRASH REPORT Process <0.9572.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:04:46.911138 +0800	1539831886	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:04:46.911382 +0800	1539831886	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9463.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:04:46.911549 +0800	1539831886	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:04:47.232543 +0800	1539831887	null:null	0	CRASH REPORT Process <0.9592.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:04:47.233275 +0800	1539831887	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:04:47.233415 +0800	1539831887	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:04:51.912757 +0800	1539831891	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:04:51.913105 +0800	1539831891	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:04:51.913260 +0800	1539831891	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9574.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:04:56.914758 +0800	1539831896	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:04:56.915256 +0800	1539831896	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:04:56.915501 +0800	1539831896	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9644.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:05:01.916766 +0800	1539831901	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:05:01.917472 +0800	1539831901	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:05:01.917663 +0800	1539831901	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9773.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:05:06.919019 +0800	1539831906	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:05:06.920159 +0800	1539831906	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:05:06.920386 +0800	1539831906	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9816.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:05:07.269234 +0800	1539831907	null:null	0	CRASH REPORT Process <0.9935.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:05:07.269688 +0800	1539831907	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:05:07.269852 +0800	1539831907	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:05:11.920804 +0800	1539831911	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:05:11.921153 +0800	1539831911	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:05:11.921309 +0800	1539831911	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9929.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:05:16.922648 +0800	1539831916	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:05:16.923113 +0800	1539831916	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:05:16.950634 +0800	1539831916	null:null	0	CRASH REPORT Process <0.10083.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:05:16.951014 +0800	1539831916	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:05:16.951242 +0800	1539831916	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.9974.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:05:16.951376 +0800	1539831916	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:05:21.951784 +0800	1539831921	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:05:21.952375 +0800	1539831921	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:05:21.952577 +0800	1539831921	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10085.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:05:26.953722 +0800	1539831926	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:05:26.954235 +0800	1539831926	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:05:26.954514 +0800	1539831926	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10141.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:05:27.308041 +0800	1539831927	null:null	0	CRASH REPORT Process <0.10283.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:05:27.308442 +0800	1539831927	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:05:27.308631 +0800	1539831927	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:05:31.955898 +0800	1539831931	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:05:31.956453 +0800	1539831931	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:05:31.956674 +0800	1539831931	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10275.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:05:36.957715 +0800	1539831936	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:05:36.958259 +0800	1539831936	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:05:36.958421 +0800	1539831936	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10336.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:05:41.959840 +0800	1539831941	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:05:41.960420 +0800	1539831941	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:05:41.960640 +0800	1539831941	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10416.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:05:46.961740 +0800	1539831946	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:05:46.962277 +0800	1539831946	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:05:46.990478 +0800	1539831946	null:null	0	CRASH REPORT Process <0.10573.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:05:46.990920 +0800	1539831946	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:05:46.991097 +0800	1539831946	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10490.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:05:46.991224 +0800	1539831946	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:05:47.346278 +0800	1539831947	null:null	0	CRASH REPORT Process <0.10587.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:05:47.346847 +0800	1539831947	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:05:47.347041 +0800	1539831947	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:05:51.991813 +0800	1539831951	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:05:51.992216 +0800	1539831951	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:05:51.992399 +0800	1539831951	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10578.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:05:56.992953 +0800	1539831956	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:05:56.993675 +0800	1539831956	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:05:56.993961 +0800	1539831956	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10666.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:06:01.994767 +0800	1539831961	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:06:01.995364 +0800	1539831961	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:06:01.995596 +0800	1539831961	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10746.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:06:06.996720 +0800	1539831966	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:06:06.997298 +0800	1539831966	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:06:06.997565 +0800	1539831966	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10839.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:06:07.383938 +0800	1539831967	null:null	0	CRASH REPORT Process <0.10899.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:06:07.384345 +0800	1539831967	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:06:07.384523 +0800	1539831967	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:06:11.998771 +0800	1539831971	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:06:11.999412 +0800	1539831971	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:06:11.999640 +0800	1539831971	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10879.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:06:17.592 +0800	1539831977	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:06:17.1038 +0800	1539831977	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:06:17.31422 +0800	1539831977	null:null	0	CRASH REPORT Process <0.11037.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:06:17.31906 +0800	1539831977	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:06:17.32047 +0800	1539831977	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.10992.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:06:17.32172 +0800	1539831977	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:06:22.32876 +0800	1539831982	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:06:22.33251 +0800	1539831982	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:06:22.33408 +0800	1539831982	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11040.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:06:27.34827 +0800	1539831987	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:06:27.35349 +0800	1539831987	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:06:27.35580 +0800	1539831987	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11160.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:06:27.421228 +0800	1539831987	null:null	0	CRASH REPORT Process <0.11210.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:06:27.421877 +0800	1539831987	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:06:27.422145 +0800	1539831987	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:06:32.36760 +0800	1539831992	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:06:32.37187 +0800	1539831992	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:06:32.37437 +0800	1539831992	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11202.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:06:37.38809 +0800	1539831997	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:06:37.39305 +0800	1539831997	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:06:37.39584 +0800	1539831997	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11325.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:06:39.38530 +0800	1539831999	leo_manager_cluster_monitor:handle_call - DOWN	269	[{node,'gateway_01@10.0.1.103'}]
[E]	manager_0@10.0.1.101	2018-10-18 11:06:42.40834 +0800	1539832002	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:06:42.41674 +0800	1539832002	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:06:42.41927 +0800	1539832002	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11362.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:06:47.42721 +0800	1539832007	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:06:47.43115 +0800	1539832007	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:06:47.71657 +0800	1539832007	null:null	0	CRASH REPORT Process <0.11513.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:06:47.71959 +0800	1539832007	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:06:47.72119 +0800	1539832007	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11455.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:06:47.72248 +0800	1539832007	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:06:47.461265 +0800	1539832007	null:null	0	CRASH REPORT Process <0.11527.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:06:47.461494 +0800	1539832007	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:06:47.461616 +0800	1539832007	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:06:52.73685 +0800	1539832012	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:06:52.74024 +0800	1539832012	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:06:52.74173 +0800	1539832012	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11516.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:06:56.108533 +0800	1539832016	leo_manager_cluster_monitor:handle_call - DOWN	269	[{node,'storage_02@10.0.1.107'}]
[E]	manager_0@10.0.1.101	2018-10-18 11:06:57.75722 +0800	1539832017	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:06:57.75908 +0800	1539832017	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:06:57.76053 +0800	1539832017	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11622.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:07:02.77828 +0800	1539832022	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:07:02.78235 +0800	1539832022	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:07:02.78395 +0800	1539832022	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11690.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:07:07.79792 +0800	1539832027	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:07:07.80101 +0800	1539832027	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:07:07.80265 +0800	1539832027	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11791.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:07:07.499465 +0800	1539832027	null:null	0	CRASH REPORT Process <0.11831.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:07:07.499771 +0800	1539832027	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:07:07.499933 +0800	1539832027	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:07:12.80886 +0800	1539832032	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:07:12.81389 +0800	1539832032	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:07:12.81630 +0800	1539832032	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11826.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:07:17.82777 +0800	1539832037	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:07:17.83540 +0800	1539832037	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:07:17.109797 +0800	1539832037	null:null	0	{module,"leo_pod_manager"},{function,"start_child/2"},{line,324},{body,{connection_error,{connection_error,econnrefused}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:07:17.110170 +0800	1539832037	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:07:17.110360 +0800	1539832037	null:null	0	CRASH REPORT Process <0.11978.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:07:17.110566 +0800	1539832037	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11930.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:07:17.110759 +0800	1539832037	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:07:22.111817 +0800	1539832042	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:07:22.112260 +0800	1539832042	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:07:22.112408 +0800	1539832042	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.11981.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:07:26.609561 +0800	1539832046	leo_manager_cluster_monitor:handle_call - DOWN	269	[{node,'gateway_02@10.0.1.104'}]
[E]	manager_0@10.0.1.101	2018-10-18 11:07:27.113827 +0800	1539832047	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:07:27.113963 +0800	1539832047	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:07:27.114150 +0800	1539832047	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.12085.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:07:27.537053 +0800	1539832047	null:null	0	{module,"leo_pod_manager"},{function,"start_child/2"},{line,324},{body,{connection_error,{connection_error,econnrefused}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:07:27.537278 +0800	1539832047	null:null	0	CRASH REPORT Process <0.12125.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:07:27.537609 +0800	1539832047	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:07:27.537771 +0800	1539832047	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:07:32.115855 +0800	1539832052	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:07:32.116207 +0800	1539832052	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:07:32.116352 +0800	1539832052	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.12121.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:07:37.117926 +0800	1539832057	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:07:37.118471 +0800	1539832057	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:07:37.118755 +0800	1539832057	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.12193.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:07:42.119803 +0800	1539832062	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:07:42.120477 +0800	1539832062	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:07:42.120754 +0800	1539832062	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.12235.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:07:47.121680 +0800	1539832067	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:07:47.122316 +0800	1539832067	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:07:47.148504 +0800	1539832067	null:null	0	CRASH REPORT Process <0.12351.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:07:47.149060 +0800	1539832067	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 11:07:47.149305 +0800	1539832067	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.12304.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 11:07:47.149533 +0800	1539832067	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:07:47.576123 +0800	1539832067	null:null	0	CRASH REPORT Process <0.12363.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:07:47.576350 +0800	1539832067	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:07:47.576469 +0800	1539832067	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:07:52.150958 +0800	1539832072	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:07:52.151403 +0800	1539832072	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:07:52.151581 +0800	1539832072	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.12353.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:07:57.152778 +0800	1539832077	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:07:57.153197 +0800	1539832077	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:07:57.153363 +0800	1539832077	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.12427.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:08:02.154863 +0800	1539832082	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:08:02.155386 +0800	1539832082	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:08:02.155627 +0800	1539832082	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.12521.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:08:07.157094 +0800	1539832087	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:08:07.158689 +0800	1539832087	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:08:07.159330 +0800	1539832087	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.12575.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 11:08:07.614741 +0800	1539832087	null:null	0	CRASH REPORT Process <0.12630.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 11:08:07.615197 +0800	1539832087	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 11:08:07.615353 +0800	1539832087	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 11:08:12.158816 +0800	1539832092	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 11:08:12.159333 +0800	1539832092	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 11:08:12.159530 +0800	1539832092	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.12621.0> exit with reason no such process or port in call to gen_server:call(<0.3142.0>, raw_status) in context child_terminated
