[E]	manager_0@10.0.1.101	2018-10-18 14:00:01.534102 +0800	1539842401	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 14:00:01.534662 +0800	1539842401	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 14:00:01.534833 +0800	1539842401	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.28354.3> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 14:00:06.535176 +0800	1539842406	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 14:00:06.535987 +0800	1539842406	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 14:00:06.536387 +0800	1539842406	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.28428.3> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 14:00:11.537179 +0800	1539842411	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 14:00:11.537845 +0800	1539842411	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 14:00:11.538152 +0800	1539842411	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.28501.3> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 14:00:16.303904 +0800	1539842416	null:null	0	{module,"leo_pod_manager"},{function,"start_child/2"},{line,324},{body,{connection_error,{connection_error,econnrefused}}}
[E]	manager_0@10.0.1.101	2018-10-18 14:00:16.304427 +0800	1539842416	null:null	0	CRASH REPORT Process <0.28665.3> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 14:00:16.304824 +0800	1539842416	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 14:00:16.305008 +0800	1539842416	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 14:00:16.539119 +0800	1539842416	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 14:00:16.539271 +0800	1539842416	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 14:00:16.539417 +0800	1539842416	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.28590.3> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 14:00:21.541077 +0800	1539842421	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 14:00:21.541525 +0800	1539842421	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 14:00:21.570780 +0800	1539842421	null:null	0	CRASH REPORT Process <0.28758.3> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 14:00:21.571014 +0800	1539842421	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 14:00:21.571161 +0800	1539842421	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.28669.3> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 14:00:21.571287 +0800	1539842421	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 14:00:26.572391 +0800	1539842426	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 14:00:26.572838 +0800	1539842426	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 14:00:26.573149 +0800	1539842426	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.28760.3> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 14:00:31.574189 +0800	1539842431	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 14:00:31.574788 +0800	1539842431	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 14:00:31.575024 +0800	1539842431	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.28821.3> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 14:00:36.342063 +0800	1539842436	null:null	0	CRASH REPORT Process <0.28972.3> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 14:00:36.342680 +0800	1539842436	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 14:00:36.342811 +0800	1539842436	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 14:00:36.576252 +0800	1539842436	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 14:00:36.576402 +0800	1539842436	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 14:00:36.576566 +0800	1539842436	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.28899.3> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 14:00:41.578108 +0800	1539842441	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 14:00:41.578639 +0800	1539842441	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 14:00:41.578807 +0800	1539842441	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.28975.3> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 14:00:46.580180 +0800	1539842446	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 14:00:46.580619 +0800	1539842446	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 14:00:46.580806 +0800	1539842446	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.29055.3> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 14:00:51.582088 +0800	1539842451	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 14:00:51.582646 +0800	1539842451	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 14:00:51.610132 +0800	1539842451	null:null	0	CRASH REPORT Process <0.29252.3> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 14:00:51.610644 +0800	1539842451	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 14:00:51.610925 +0800	1539842451	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.29171.3> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 14:00:51.611124 +0800	1539842451	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 14:00:56.378956 +0800	1539842456	null:null	0	CRASH REPORT Process <0.29335.3> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 14:00:56.379429 +0800	1539842456	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 14:00:56.379554 +0800	1539842456	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 14:00:56.612159 +0800	1539842456	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 14:00:56.612298 +0800	1539842456	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 14:00:56.612453 +0800	1539842456	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.29254.3> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 14:01:01.614133 +0800	1539842461	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 14:01:01.614660 +0800	1539842461	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 14:01:01.614892 +0800	1539842461	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.29339.3> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 14:01:06.616103 +0800	1539842466	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 14:01:06.616750 +0800	1539842466	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 14:01:06.616941 +0800	1539842466	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.29426.3> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 14:01:11.617219 +0800	1539842471	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 14:01:11.617650 +0800	1539842471	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 14:01:11.617907 +0800	1539842471	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.29488.3> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 14:01:16.416909 +0800	1539842476	null:null	0	CRASH REPORT Process <0.29629.3> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 14:01:16.417675 +0800	1539842476	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[W]	manager_0@10.0.1.101	2018-10-18 14:01:16.417815 +0800	1539842476	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 14:01:16.618238 +0800	1539842476	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 14:01:16.618447 +0800	1539842476	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 14:01:16.618615 +0800	1539842476	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.29563.3> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[E]	manager_0@10.0.1.101	2018-10-18 14:01:21.620353 +0800	1539842481	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 14:01:21.620690 +0800	1539842481	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 14:01:21.649964 +0800	1539842481	null:null	0	CRASH REPORT Process <0.29735.3> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
[E]	manager_0@10.0.1.101	2018-10-18 14:01:21.650368 +0800	1539842481	null:null	0	Supervisor leo_rpc_client_manager_11_at_13075_sup had child leo_rpc_client_manager_11_at_13075 started with leo_pod_manager:start_link(leo_rpc_client_manager_11_at_13075, 16, 16, leo_rpc_client_conn, [manager_11,"10.16.0.247",13075,0], #Fun<leo_rpc_client_sup.0.73440599>) at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
[E]	manager_0@10.0.1.101	2018-10-18 14:01:21.650531 +0800	1539842481	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.29633.3> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
[W]	manager_0@10.0.1.101	2018-10-18 14:01:21.650676 +0800	1539842481	null:null	0	{module,"leo_rpc_client_sup"},{function,"start_child/3"},{line,106},{body,{{shutdown,{failed_to_start_child,leo_rpc_client_manager_11_at_13075,{connection_error,{connection_error,econnrefused}}}},{child,undefined,leo_rpc_client_manager_11_at_13075,{leo_pod_sup,start_link,[leo_rpc_client_manager_11_at_13075,16,16,leo_rpc_client_conn,[manager_11,"10.16.0.247",13075,0],#Fun<leo_rpc_client_sup.0.73440599>]},permanent,10000,supervisor,[leo_pod_sup]}}}
[E]	manager_0@10.0.1.101	2018-10-18 14:01:26.652159 +0800	1539842486	gen_server:call	0	gen_server leo_rpc_client_manager terminated with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:call/2 line 204
[E]	manager_0@10.0.1.101	2018-10-18 14:01:26.653067 +0800	1539842486	gen_server:call	0	CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in gen_server:terminate/7 line 812
[E]	manager_0@10.0.1.101	2018-10-18 14:01:26.653322 +0800	1539842486	gen_server:call	0	Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.29737.3> exit with reason no such process or port in call to gen_server:call(<0.3130.0>, raw_status) in context child_terminated
